---
driver:
  name: localhost

provisioner:
  name: chef_zero

platforms:
  - name: localhost

suites:
  - name: create_file
    run_list:
      - recipe[kitchen-localhost-test::create_file]
  - name: delete_file
    run_list:
      - recipe[kitchen-localhost-test::delete_file]
