language: ruby

cache:
  - bundler
  - directories:
    - /tmp/verifier/gems
sudo: true

branches:
  only:
    - master

install:
  - bundle update

script:
  - bundle exec rake && bundle exec kitchen test -c 2

rvm:
- ruby-head
- 2.0.0
- 1.9.3
