language: objective-c

branches:
  only:
    - master

install:
  - curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
  - chef exec bundle update

script:
  - chef exec bundle exec kitchen test -c 2
