branches:
  only:
    - master

install:
  - cinst chefdk
  - SET PATH=C:\opscode\chefdk\bin;%PATH%

build_script:
  - chef exec bundle install

test_script:
  - chef exec bundle exec rake
  - chef exec bundle exec kitchen test
