branches:
  only:
    - master

environment:
  matrix:
    - ruby_version: 222
    - ruby_version: 200
    - ruby_version: 193

cache:
  - C:\Ruby%ruby_version%\bin
  - C:\Ruby%ruby_version%\lib\ruby\gems

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem install bundler

build_script:
  - bundle install

test_script:
  - bundle exec rake
  - bundle exec kitchen test
